### ISSUE TITLE
Колонка цветовая, разделенная на 1-N столбцов.

### ISSUE THREAD

**Issue by dgrechka** [itislab/CoreSampleAnnotation#34]
От Олега.

один из вариантов колонок на полотне разметки.

"Цветом заливается один, или несколько столбцов в зависимости от градации процесса. Тип заливки – возможность выбора для данного интервала. Вариант – такая колонка только с делениями без заливки."

**Comment by lucymukh** [comment]
Закрываю до повторного запроса.
