### ISSUE TITLE
Детальное фотографирование

### ISSUE THREAD

**Issue by dgrechka** [itislab/CoreSampleAnnotation#40]
от Олега:

Относительно возможности детального фотографирования - можно по кнопке запускать фотокамеру, делать крупноплановый снимок, а далее - сохранять его в отдельную директорию с присвоением имени и глубины. С последующей возможностью формировать на выходе ексельный файл с номерами по-порядку, именами файлов и глубинами.
С уважением,
Олег

**Comment by lucymukh** [comment]
Закрываю до повторного запроса.
